# External gems
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata

# Site settings
title: R
subtitle: My personal page for my projects
email: effetti@gmail.com
name: Riccardo B. Desantis
description: >
  My personal page for my projects.
baseurl: "/" # /
#baseurl: "/centrarium/" # the subpath of your site, e.g. /blog/
url: https://rickdesantis.js.org # the base hostname & protocol for your site
cover: assets/header_image.jpg
logo: assets/logo.png

# Build settings
markdown: kramdown

# Disqus comments
disqus_shortname: deadware

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: projects
    desc: Posts describing my projects.

  - cat: others
    desc: Posts not about my projects.

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: GitHub
    icon: github
    username: rickdesantis
    url: https://github.com/rickdesantis
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: rickdesantis
    url: https://www.linkedin.com/in/rickdesantis
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: "?mini=true"
    share_link: "&amp;url="

  - name: Twitter
    icon: twitter
    username: "@rickdesantis"
    url: https://twitter.com/rickdesantis
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="

  - name: Facebook
    icon: facebook
    username: riccardo.desantis
    url: https://www.facebook.com/riccardo.desantis
    desc: Friend me on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: "?t="
    share_link: "&amp;u="

  - name: Skype
    icon: skype
    username: riccardo.ft
    url: http://www.skype.com
    desc: Add me on Skype
    share_url:
    share_title:
    share_link:

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: assets/logo.png
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: image/png

    twitter_image: assets/logo.png
